# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(050019)
$foreground = rgb(FBF9F4)
$color0 = rgb(050019)
$color1 = rgb(1E2980)
$color2 = rgb(5B5091)
$color3 = rgb(5856A6)
$color4 = rgb(8F73A1)
$color5 = rgb(8F73A1)
$color6 = rgb(B8B3A8)
$color7 = rgb(F2EEE7)
$color8 = rgb(A9A7A2)
$color9 = rgb(2837AB)
$color10 = rgb(796BC2)
$color11 = rgb(7573DE)
$color12 = rgb(BF99D6)
$color13 = rgb(BF99D6)
$color14 = rgb(F5EEE0)
$color15 = rgb(F2EEE7)
