#############################################
# Gesture Configuration
#
# Touchpad gestures for workspace switching,
# overview toggle, and cursor zoom.
#
# See: https://wiki.hyprland.org/Configuring/Variables/#gestures
#############################################

gestures {
  # 3-finger horizontal: workspace switch
  gesture = 3, horizontal, workspace
  workspace_swipe_distance = 500
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = true

  # 4-finger up: desktop overview
  gesture = 4, up, dispatcher, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 1.5}')"
  # 4-finger down: zoom out
  gesture = 4, down, dispatcher, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 1.5}')"
  # 3-finger up: overview toggle
  gesture = 3, up, dispatcher, exec, $scriptsDir/utils/OverviewToggle.sh
}
