# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B2B2B4
background         #100000
cursor             #908486

active_tab_foreground     #100000
active_tab_background     #B2B2B4
inactive_tab_foreground   #B2B2B4
inactive_tab_background   #100000

active_border_color   #B2B2B4
inactive_border_color #100000
bell_border_color     #693A33

color0      #241917
color1		#693A33
color2		#524041
color3		#50302D
color4		#1F1D21
color5		#1A1B20
color6		#1A1B20
color7		#89898C
color8		#606062
color9		#8C4D44
color10		#6D5557
color11		#6B403C
color12		#2A272C
color13		#23242A
color14		#23242A
color15		#89898C
