#############################################
# Layer Rules
#
# Blur and behavior for Wayland layers:
# rofi, notifications, quickshell overview.
#
# See: https://wiki.hyprland.org/Configuring/Layer-Rules/
#############################################

layerrule = match:namespace rofi, blur on
layerrule = match:namespace notifications, blur on
layerrule = match:namespace quickshell:overview, blur on
layerrule = match:namespace quickshell:overview, ignore_alpha 0.5
