#############################################
# Application Defaults
#
# Default terminal, file manager, editor,
# and search engine used by keybindings
# and scripts.
#############################################

env = EDITOR,nvim
$Search_Engine = "https://www.google.com/search?q={}"
