return {
    "ibhagwan/fzf-lua",
    dependencies = { "echasnovski/mini.icons" },
    opts = {},
    keys = {
        { "<leader>ff", function() require("fzf-lua").files() end, desc = "Find Files" },
        { "<leader>fg", function() require("fzf-lua").live_grep() end, desc = "Live Grep" },
        { "<leader>fc", function() require("fzf-lua").files({ cwd = vim.fn.stdpath("config") }) end, desc = "Find in Config" },
        { "<leader>fh", function() require("fzf-lua").helptags() end, desc = "Find Help" },
        { "<leader>fk", function() require("fzf-lua").keymaps() end, desc = "Find Keymaps" },
        { "<leader>fb", function() require("fzf-lua").builtin() end, desc = "Find Builtin" },
        { "<leader>fw", function() require("fzf-lua").grep_cword() end, desc = "Find Word" },
        { "<leader>fW", function() require("fzf-lua").grep_cWORD() end, desc = "Find WORD" },
        { "<leader>fd", function() require("fzf-lua").diagnostics_document() end, desc = "Find Diagnostics" },
        { "<leader>fr", function() require("fzf-lua").resume() end, desc = "Find Resume" },
        { "<leader>fo", function() require("fzf-lua").oldfiles() end, desc = "Find Old Files" },
        { "<leader><leader>", function() require("fzf-lua").buffers() end, desc = "Find Buffers" },
        { "<leader>/", function() require("fzf-lua").lgrep_curbuf() end, desc = "Grep Current Buffer" },
    },
}
