#############################################
# Cursor Configuration
#
# Cursor theme, size, and hardware cursor
# behavior. Bibata-Modern-Ice via hyprcursor.
#
# See: https://wiki.hyprland.org/Configuring/Variables/#cursor
#############################################

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors = 1
  enable_hyprcursor = true
  warp_on_change_workspace = 2
  no_warps = true
}
