#############################################
# Compositor Core
#
# Dwindle and Master layout definitions,
# general compositor behavior, XWayland,
# render settings, and cursor behavior.
#############################################

dwindle {
  preserve_split = true
  special_scale_factor = 0.8
}

master {
  new_status = master
  new_on_top = 1
  mfact = 0.5
}

general {
  resize_on_border = true
  layout = dwindle
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

xwayland {
  enabled = true
  force_zero_scaling = true
}

render {
  direct_scanout = 0
}

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors = 1
  enable_hyprcursor = true
  warp_on_change_workspace = 2
  no_warps = true
}
